package view;

import controller.ControllerNotasDB;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import model.ModelNota;

/**
 *
 * @author Gelvazio Camargo
 */
public class ViewManutencaoNota extends javax.swing.JFrame {


    ViewConsultaNota cons = new ViewConsultaNota(this, true);
    ViewPesquisaProfessor prof = new ViewPesquisaProfessor(this, true);
    ViewpesquisaAluno alu = new ViewpesquisaAluno(this, true);
    ViewPesquisaMateria mate = new ViewPesquisaMateria(this, true);
    

    ControllerNotasDB notadb = new ControllerNotasDB();

    public ViewManutencaoNota() {
        initComponents();
        this.setLocationRelativeTo(null);
        edtCodigo.requestFocus();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnConsulta = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        edtcodigoprofessor = new javax.swing.JTextField();
        edtcodigomateria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edtcodigoaluno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        edtData = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edtNota = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edtnomeprofessor = new javax.swing.JTextField();
        edtnomemateria = new javax.swing.JTextField();
        edtnomealuno = new javax.swing.JTextField();
        btnPesquisamateria = new javax.swing.JButton();
        btnPesquisaAluno = new javax.swing.JButton();
        btnPescquisaProf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Notas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 650, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Código nota");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("codigo professor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        edtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodigoActionPerformed(evt);
            }
        });
        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, -1));

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Valid Green.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 130, 40));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Remove Red.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.setPreferredSize(new java.awt.Dimension(101, 41));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 130, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.setPreferredSize(new java.awt.Dimension(101, 41));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 130, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 610, 10));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 610, 10));

        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Search.png"))); // NOI18N
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 40, 40));

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Add.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 40, 40));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Red.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 130, 40));

        edtcodigoprofessor.setEnabled(false);
        getContentPane().add(edtcodigoprofessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, -1));

        edtcodigomateria.setEnabled(false);
        edtcodigomateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtcodigomateriaActionPerformed(evt);
            }
        });
        edtcodigomateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtcodigomateriaKeyPressed(evt);
            }
        });
        getContentPane().add(edtcodigomateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("codigo materia");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        edtcodigoaluno.setEnabled(false);
        getContentPane().add(edtcodigoaluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("codigo aluno");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        edtData.setEnabled(false);
        getContentPane().add(edtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 410, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("data");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        edtNota.setEnabled(false);
        getContentPane().add(edtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 410, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("nota");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        edtnomeprofessor.setEnabled(false);
        edtnomeprofessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtnomeprofessorActionPerformed(evt);
            }
        });
        getContentPane().add(edtnomeprofessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 270, -1));

        edtnomemateria.setEnabled(false);
        getContentPane().add(edtnomemateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 270, -1));

        edtnomealuno.setEnabled(false);
        getContentPane().add(edtnomealuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 270, -1));

        btnPesquisamateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Search.png"))); // NOI18N
        btnPesquisamateria.setEnabled(false);
        btnPesquisamateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisamateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisamateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 40, 40));

        btnPesquisaAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Search.png"))); // NOI18N
        btnPesquisaAluno.setEnabled(false);
        btnPesquisaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisaAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 40, 40));

        btnPescquisaProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Search.png"))); // NOI18N
        btnPescquisaProf.setEnabled(false);
        btnPescquisaProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPescquisaProfActionPerformed(evt);
            }
        });
        getContentPane().add(btnPescquisaProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 40, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
       // Seta os dados da tela no modelo de produto
        String auxCodigonota = edtCodigo.getText();
        String auxCodigoprofessor = edtcodigoprofessor.getText();
        String auxCodigoaluno = edtcodigoaluno.getText();
        String auxData = edtData.getText();
        String auxCodigomateria = edtcodigomateria.getText();
        String auxNota = edtNota.getText();

        // valida campos vazios
        if(validaCamposVazios(auxCodigonota,auxCodigoprofessor,auxCodigoaluno,auxData,auxCodigomateria,auxNota )){
            int codigonota = Integer.parseInt(auxCodigonota);
            int codigoprofessor = Integer.parseInt(auxCodigoprofessor);
            int codigoaluno = Integer.parseInt(auxCodigoaluno);
            int codigomateria = Integer.parseInt(auxCodigomateria);
            double Notas = Double.parseDouble(auxNota);

            String auxDia = auxData.substring(0,2);
            String auxMes = auxData.substring(3,5);
            String auxAno = auxData.substring(6,10);

            int ano = Integer.parseInt(auxAno);
            int mes = Integer.parseInt(auxMes);
            int dia = Integer.parseInt(auxDia);
            
            ano = ano - 1900;
            mes = mes - 1;

            java.sql.Date dataNota = new java.sql.Date(ano,mes,dia);

            ModelNota notas = new ModelNota(codigoprofessor, codigomateria, codigoaluno, codigonota, dataNota, Notas);

            ModelNota notaBanco = notadb.getNota(codigonota);
            if (notaBanco.getCodigonota() > 0) {
                if(notadb.gravarAlteracaoNotas(notas)){
                    JOptionPane.showMessageDialog(null, "Nota alterada com sucesso!");

                    limpaCampos();

                    habilitaCampos(false);

                    edtCodigo.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao gravar alteração da nota!");
                }
            } else {
                if(notadb.gravarInsercaoNota(notas)){
                    JOptionPane.showMessageDialog(null, "Nota inserida com sucesso!");

                    limpaCampos();

                    habilitaCampos(false);

                    edtCodigo.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao inserir nota!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Existem campos não preenchidos!");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         int codigoNota = Integer.parseInt(edtCodigo.getText());


            if (notadb.excluirNota(codigoNota)) {
                JOptionPane.showMessageDialog(null, "Nota excluída com sucesso!");

                limpaCampos();

                habilitaCampos(false);

                edtCodigo.requestFocus();
            }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void edtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_TAB)) {
            if (edtCodigo.getText().equals("")) {

                edtCodigo.setText(String.valueOf(notadb.getUltimoCodigo("tbnota", "codigo")));

                habilitaCampos(true);

                edtCodigo.requestFocus();
            } else {
                int codigonota = Integer.parseInt(edtCodigo.getText());
//                ModelNota  = new ModelNota();
                ModelNota notaBanco = notadb.getNota(codigonota);
                if (notaBanco.getCodigonota() > 0) {
                    //edtcodigoaluno.setText(notaBanco.getcodigoaluno());
                     String auxcodprofessor = "" + notaBanco.getCodigoprofessor();
                    edtcodigoprofessor.setText(auxcodprofessor);
                     String auxcodmateria = "" + notaBanco.getCodigomateria();
                    edtcodigomateria.setText(auxcodmateria);
                     String auxcodaluno = "" + notaBanco.getCodigoaluno();
                    edtcodigoaluno.setText(auxcodaluno);
                    String auxdata = "" + notaBanco.getData();
                    
                    // formatar a data do banco 
                     
                    LocalDate hoje = LocalDate.now();

                    String auxData = "" + auxdata;
                    String auxAno = auxData.substring(0,4);
                    String auxMes = auxData.substring(5,7);
                    String auxDia = auxData.substring(8,10);

                    String auxNovaData = auxDia + "/" + auxMes + "/" + auxAno;
                    
                    edtData.setText(auxNovaData);
                    
                    String auxnota = "" + notaBanco.getNota();
                    edtNota.setText(auxnota);

                    habilitaCampos(true);
                    edtcodigoaluno.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "nota não existe!");

                    habilitaCampos(false);

                    edtCodigo.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_edtCodigoKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void edtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodigoActionPerformed

    }//GEN-LAST:event_edtCodigoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCampos();
        habilitaCampos(false);
        edtCodigo.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        edtCodigo.setText(String.valueOf(notadb.getUltimoCodigo("tbnota", "codigo")));

        habilitaCampos(true);
        edtnomeprofessor.setVisible(true);
        edtnomemateria.setVisible(true);
        edtnomealuno.setVisible(true);
        btnExcluir.setVisible(false);

        edtcodigoaluno.requestFocus();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed

        cons.setVisible(true);
        edtCodigo.setText(String.valueOf(cons.codigo));
        edtnomeprofessor.setVisible(false);
        edtnomemateria.setVisible(false);
        edtnomealuno.setVisible(false);
        btnExcluir.setVisible(true);
        edtCodigo.requestFocus();
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void edtcodigomateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtcodigomateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtcodigomateriaActionPerformed

    private void edtcodigomateriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtcodigomateriaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtcodigomateriaKeyPressed

    private void edtnomeprofessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtnomeprofessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtnomeprofessorActionPerformed

    private void btnPescquisaProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPescquisaProfActionPerformed
        habilitaCampos(true);
        prof.setVisible(true);
        edtnomeprofessor.setVisible(true);
        edtcodigoprofessor.setText(String.valueOf(prof.codigo));
        edtcodigoprofessor.requestFocus();
        edtnomeprofessor.setText(String.valueOf(prof.nome));
        edtnomeprofessor.requestFocus();
        
        
    }//GEN-LAST:event_btnPescquisaProfActionPerformed

    private void btnPesquisamateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisamateriaActionPerformed
    mate.setVisible(true);
    edtnomemateria.setVisible(true);
        edtcodigomateria.setText(String.valueOf(mate.codigo));
        edtcodigomateria.requestFocus();
        edtnomemateria.setText(String.valueOf(mate.nome));
        edtnomemateria.requestFocus();
    }//GEN-LAST:event_btnPesquisamateriaActionPerformed

    private void btnPesquisaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaAlunoActionPerformed
      alu.setVisible(true);
      edtnomealuno.setVisible(true);
        edtcodigoaluno.setText(String.valueOf(alu.codigo));
        edtnomealuno.setText(String.valueOf(alu.nome));
       // habilitaCampos(true);
        edtcodigoaluno.requestFocus();
        edtnomealuno.requestFocus();
    }//GEN-LAST:event_btnPesquisaAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewManutencaoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewManutencaoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewManutencaoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewManutencaoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewManutencaoNota().setVisible(true);
            }
        });
    }

    public void habilitaCampos(boolean habilita) {
        edtcodigoaluno.setEnabled(habilita);
        edtcodigomateria.setEnabled(habilita);
        edtCodigo.setEnabled(habilita);
        edtNota.setEnabled(habilita);
        edtData.setEnabled(habilita);
        edtcodigoprofessor.setEnabled(habilita);
        edtnomeprofessor.setEnabled(habilita);
        edtnomemateria.setEnabled(habilita);
        edtnomealuno.setEnabled(habilita);

        btnGravar.setEnabled(habilita);
        btnExcluir.setEnabled(habilita);
        btnCancelar.setEnabled(habilita);
        btnPescquisaProf.setEnabled(habilita);
        btnPesquisamateria.setEnabled(habilita);
        btnPesquisaAluno.setEnabled(habilita);
        //btnPesquisaData.setEnabled(habilita);
        

        edtCodigo.setEnabled(!habilita);
        btnConsulta.setEnabled(!habilita);
        btnAdicionar.setEnabled(!habilita);
        btnSair.setEnabled(!habilita);
        
    }

    public void limpaCampos() {
        edtCodigo.setText("");
        edtcodigoaluno.setText("");
        edtcodigomateria.setText("");
        edtNota.setText("");
        edtData.setText("");
        edtcodigoprofessor.setText("");
        edtnomeprofessor.setText("");
        edtnomemateria.setText("");
        edtnomealuno.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnPescquisaProf;
    private javax.swing.JButton btnPesquisaAluno;
    private javax.swing.JButton btnPesquisamateria;
    private javax.swing.JButton btnSair;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtData;
    private javax.swing.JTextField edtNota;
    private javax.swing.JTextField edtcodigoaluno;
    private javax.swing.JTextField edtcodigomateria;
    private javax.swing.JTextField edtcodigoprofessor;
    private javax.swing.JTextField edtnomealuno;
    private javax.swing.JTextField edtnomemateria;
    private javax.swing.JTextField edtnomeprofessor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables

    private boolean validaCamposVazios(String auxCodigonota, String auxCodigoprofessor, String auxCodigoaluno, String auxData, String auxCodigomateria, String auxNota) {
       if(auxCodigonota.equals("")){
            return false;
        }

        if(auxCodigoprofessor.equals("")){
            return false;
        }

        if(auxCodigoaluno.equals("")){
            return false;
        }
        if(auxData.equals("")){
            return false;
        }
        if(auxCodigomateria.equals("")){
            return false;
        }
        if(auxNota.equals("")){
            return false;
        }

        return true;
    }
        protected Date getDataFormatada(String auxData) {
        //Conversao de Datas e Horas
        //Inicio
        java.text.DateFormat formatter = new java.text.SimpleDateFormat("dd/MM/yyyy");
        formatter.setLenient(false);

        //Inicia com null as variaveis
        java.util.Date javautilDateDataAlteracao = null;

        //Altera para java.util.date a String do campo de texto
        try {
            javautilDateDataAlteracao = (java.util.Date) formatter.parse(auxData);
        } catch (Exception e) {
        }

        //Altera de java.util.date para java.sql.date
        java.sql.Date DataAlteracao = new java.sql.Date(javautilDateDataAlteracao.getTime());

        Date dt_alt = DataAlteracao;
//
//        MOdelItem - private Date dt_alt;

        return dt_alt;

    }
    }

